name: raid_calc
description: Raid Calc (Safe)
environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_mobile_ads: ^5.0.0
  # …le altre tue dipendenze (i18n, ecc.)

flutter:
  uses-material-design: true
  assets:
    - assets/raidComplete_data.json
    - assets/lang/it.json
    - assets/lang/en.json
    - assets/lang/de.json
    - assets/lang/fr.json
    - assets/lang/es.json
    - assets/lang/ru.json
    - assets/lang/nl.json
