name: raid_calc
description: Raid Calculator
version: 1.0.0+1 # +1 = versionCode
environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_mobile_ads: ^5.0.0
  # …le altre tue dipendenze (i18n, ecc.)

flutter:
  uses-material-design: true
  assets:
    - assets/raidComplete_data.json
    - assets/lang/
